version: 0.2

env:
  parameter-store:
    DOCKER_USER: /docker/build/user
    DOCKER_TOKEN: /docker/build/token
    PREV_GIT_SHA: /codebuild/state/docker-monorepo/prev-git-sha
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
    BUILDX_VERSION: v0.5.1
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      # - yum update -y
      - echo "Installing Buildx plugin..."
      - wget https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-${BUILDX_VERSION}.linux-amd64
      - chmod a+x buildx-$BUILDX_VERSION.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-$BUILDX_VERSION.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - echo "Installing cross platform tools..."
      - docker run --privileged --rm tonistiigi/binfmt --install all
  pre_build:
    commands:
      - docker version
      - docker buildx create --name mybuilder
      - docker buildx use mybuilder
      - docker buildx inspect --bootstrap
      - echo "Logging in to Docker..."
      - echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin
      - echo "Logging in to Amazon ECR..."
      - REPO="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO
  build:
    commands:
      - src/.ci/build.sh
  post_build:
    commands:
      - docker logout
      - docker logout $REPO
